# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# 20 Players
Player.create!(name: "Erling Haland", email: "erling@example.com", password: "password", address: "1 Devon Ave, Chicago, Illinois 60645", position: "Forward", dob: Date.new(2000, 07, 21), level: "recreational")
Player.create!(name: "Lionel Messi", email: "lionel@example.com", password: "password", address: "2 Sacramento Ave, Chicago, IL 60645", position: "Midfield", dob: Date.new(1987, 06, 24), level: "recreational")
Player.create!(name: "Joao Felix", email: "joao@example.com", password: "password", address: "3 Devon Ave, Chicago, Illinois 60645", position: "Midfield", dob: Date.new(1999, 11, 10), level: "recreational")
Player.create!(name: "Rafael Marquez", email: "rafael@example.com", password: "password", address: "4 North California Ave, Chicago, IL 60645", position: "Defender", dob: Date.new(1979, 02, 13), level: "recreational")
Player.create!(name: "Manuel Neuer", email: "manuel@example.com", password: "password", address: "5 Devon Ave, Chicago, Illinois 60645", position: "Goalkeeper", dob: Date.new(1986, 03, 27), level: "recreational")
Player.create!(name: "Megan Rapinoe", email: "megan@example.com", password: "password", address: "1 Sacramento Ave, Chicago, IL 60645", position: "Midfield", dob: Date.new(1985, 07, 05), level: "recreational")
Player.create!(name: "Marta Vieira da Silva", email: "marta@example.com", password: "password", address: "2 Devon Ave, Chicago, IL 60645", position: "Forward", dob: Date.new(1986, 02, 19), level: "recreational")
Player.create!(name: "Joseline Montoya", email: "joseline@example.com", password: "password", address: "3 Sacramento Ave, Chicago, IL 60645", position: "Forward", dob: Date.new(2000, 07, 03), level: "recreational")
Player.create!(name: "Adrianna Franch", email: "adrianna@example.com", password: "password", address: "4 Devon Ave, Chicago, IL 60645", position: "Goalkeeper", dob: Date.new(1990, 11, 12), level: "recreational")
Player.create!(name: "Julie Ertz", email: "julie@example.com", password: "password", address: "5 North California Ave, Chicago, IL 60645", position: "Defender", dob: Date.new(1992, 04, 06), level: "recreational")
Player.create!(name: "Ernesto Melchor", email: "ernesto@example.com", password: "password", address: "88 North California Ave, Chicago, IL 60645", position: "Forward", dob: Date.new(1988, 8, 8), level: "recreational", admin: true)
Player.create!(name: "Peter Jang", email: "peter@example.com", password: "password", address: "22 Devon Ave, Chicago, Illinois 60645", position: "Forward", dob: Date.new(1981, 07, 21), level: "recreational")
Player.create!(name: "Yesenia Marquez", email: "yesenia@example.com", password: "password", address: "22 Sacramento Ave, Chicago, IL 60645", position: "Midfield", dob: Date.new(1977, 06, 24), level: "recreational")
Player.create!(name: "Arturo Vergara", email: "arturo@example.com", password: "password", address: "33 Devon Ave, Chicago, Illinois 60645", position: "Midfield", dob: Date.new(1996, 11, 10), level: "recreational")
Player.create!(name: "Rocio Rodriguez", email: "rocio@example.com", password: "password", address: "43 North California Ave, Chicago, IL 60645", position: "Defender", dob: Date.new(1979, 02, 13), level: "recreational")
Player.create!(name: "Jim Gonzalez", email: "jim@example.com", password: "password", address: "54 Devon Ave, Chicago, Illinois 60645", position: "Goalkeeper", dob: Date.new(1983, 03, 27), level: "recreational")
Player.create!(name: "Alexia Monro", email: "alexia@example.com", password: "password", address: "14 Sacramento Ave, Chicago, IL 60645", position: "Midfield", dob: Date.new(1990, 07, 05), level: "recreational")
Player.create!(name: "Miriam Altamirano", email: "miriam@example.com", password: "password", address: "25 Devon Ave, Chicago, IL 60645", position: "Forward", dob: Date.new(1990, 02, 19), level: "recreational")
Player.create!(name: "Hope Sanders", email: "hope@example.com", password: "password", address: "53 Sacramento Ave, Chicago, IL 60645", position: "Forward", dob: Date.new(1990, 07, 03), level: "recreational")
Player.create!(name: "James Madison", email: "james@example.com", password: "password", address: "46 Devon Ave, Chicago, IL 60645", position: "Goalkeeper", dob: Date.new(1990, 11, 12), level: "recreational")

# 20 Fields
Field.create!(name: "Chicago Celtic Training Field", address: "5099 N Albany Ave, Chicago, IL 60625", open_time: DateTime.new(2020, 1, 1, 8, 00, 00), close_time: DateTime.new(2050, 1, 1, 8, 00, 00), image_url: "https://images.unsplash.com/photo-1570277756464-146a053f8a0c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80")
Field.create!(name: "Clark Turf Field", address: "3373 N Rockwell St, Chicago, IL 60618", open_time: DateTime.new(2020, 1, 1, 8, 00, 00), close_time: DateTime.new(2050, 1, 1, 8, 00, 00), image_url: "https://images.pexels.com/photos/1171084/pexels-photo-1171084.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260")
Field.create!(name: "Humboldt Cage", address: "1335 Marin Dr, Chicago, IL 60622", open_time: DateTime.new(2020, 1, 1, 8, 00, 00), close_time: DateTime.new(2050, 1, 1, 8, 00, 00), image_url: "https://images.unsplash.com/photo-1521579971123-1192931a1452?ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80")
Field.create!(name: "Lerner Park Soccer Field", address: "7000 N Sacramento Ave, Chicago, IL 60645", open_time: DateTime.new(2020, 1, 1, 8, 00, 00), close_time: DateTime.new(2050, 1, 1, 8, 00, 00), image_url: "https://images.pexels.com/photos/1375148/pexels-photo-1375148.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260")
Field.create!(name: "Pottawattomie Park", address: "7340 N Rogers Ave, Chicago, IL 60626", open_time: DateTime.new(2020, 1, 1, 8, 00, 00), close_time: DateTime.new(2050, 1, 1, 8, 00, 00), image_url: "https://images.unsplash.com/photo-1510526292299-20af3f62d453?ixlib=rb-1.2.1&auto=format&fit=crop&w=1428&q=80")
Field.create!(name: "Queen of All Saints Field", address: "4715 W Devon Ave, Chicago, IL 60646", open_time: DateTime.new(2020, 1, 1, 8, 00, 00), close_time: DateTime.new(2050, 1, 1, 8, 00, 00), image_url: "https://images.pexels.com/photos/3459633/pexels-photo-3459633.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260")
Field.create!(name: "Peterson Park Soccer Field", address: "5801 N Pulaski Rd, Chicago, IL 60646", open_time: DateTime.new(2020, 1, 1, 8, 00, 00), close_time: DateTime.new(2050, 1, 1, 8, 00, 00), image_url: "https://images.unsplash.com/photo-1546717003-caee5f93a9db?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1342&q=80")
Field.create!(name: "Ogden Park Soccer Field", address: "6500 S. Racine Ave. Chicago, IL 60636", open_time: DateTime.new(2020, 1, 1, 8, 00, 00), close_time: DateTime.new(2050, 1, 1, 8, 00, 00), image_url: "https://images.pexels.com/photos/2935982/pexels-photo-2935982.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260")
Field.create!(name: "Sherwood Park Soccer Field", address: "5701 S Shields Ave, Chicago, IL 60621", open_time: DateTime.new(2020, 1, 1, 8, 00, 00), close_time: DateTime.new(2050, 1, 1, 8, 00, 00), image_url: "https://images.pexels.com/photos/1302514/pexels-photo-1302514.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260")
Field.create!(name: "Douglas Park Soccer Field", address: "S Farrar Dr, Chicago, IL 60623", open_time: DateTime.new(2020, 1, 1, 8, 00, 00), close_time: DateTime.new(2050, 1, 1, 8, 00, 00), image_url: "https://images.unsplash.com/photo-1546717003-caee5f93a9db?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1342&q=80")
Field.create!(name: "Armour Square Park Soccer Field", address: "3357 S Shields Ave, Chicago, IL 60616", open_time: DateTime.new(2020, 1, 1, 8, 00, 00), close_time: DateTime.new(2050, 1, 1, 8, 00, 00), image_url: "https://images.unsplash.com/photo-1464295440335-ee082a75ccca?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80")
Field.create!(name: "Foster Turf Field", address: "Lakefront Trail, Chicago, IL 60640", open_time: DateTime.new(2020, 1, 1, 8, 00, 00), close_time: DateTime.new(2050, 1, 1, 8, 00, 00), image_url: "https://images.pexels.com/photos/2277980/pexels-photo-2277980.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260")
Field.create!(name: "Davis Square Park Field", address: "4430 S Marshfield Ave, Chicago, IL 60609", open_time: DateTime.new(2020, 1, 1, 8, 00, 00), close_time: DateTime.new(2050, 1, 1, 8, 00, 00), image_url: "https://images.pexels.com/photos/2935979/pexels-photo-2935979.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500")
Field.create!(name: "Lincoln Park Turf Field", address: "1778 N John C, N Cannon Dr, Chicago, IL 60614", open_time: DateTime.new(2020, 1, 1, 8, 00, 00), close_time: DateTime.new(2050, 1, 1, 8, 00, 00), image_url: "https://www.44thward.org/wp-content/uploads/2020/02/20190814-Diversey-Community-Meeting_Presentation_Reduced-20-1920x525-1-1920x525.jpg")
Field.create!(name: "Allstate Field", address: "1440 N Humboldt Dr, Chicago, IL 60622", open_time: DateTime.new(2020, 1, 1, 8, 00, 00), close_time: DateTime.new(2050, 1, 1, 8, 00, 00), image_url: "http://www.kickitsocial.net/uploads/2/1/6/3/21631706/6772801_1_orig.jpg")
Field.create!(name: "Parker Field", address: "30 W Webster Ave, Chicago, IL 60614", open_time: DateTime.new(2020, 1, 1, 8, 00, 00), close_time: DateTime.new(2050, 1, 1, 8, 00, 00), image_url: "https://www.kieferusa.com/wp-content/uploads/2015/08/francis-parker-school-artificial-soccer-turf-kieferusa.jpg")
Field.create!(name: "Horner Park Mini-Pitch", address: "2741 W Montrose Ave, Chicago, IL 60618", open_time: DateTime.new(2020, 1, 1, 8, 00, 00), close_time: DateTime.new(2050, 1, 1, 8, 00, 00), image_url: "https://assets.chicagoparkdistrict.com/s3fs-public/inline-images/Horner%20Mini%20Pitch%20-%20for%20web-1.jpg")
Field.create!(name: "Hoyne Athletic Field", address: "6336 N Hoyne Ave, Chicago, IL 60626", open_time: DateTime.new(2020, 1, 1, 8, 00, 00), close_time: DateTime.new(2050, 1, 1, 8, 00, 00), image_url: "https://images.unsplash.com/photo-1557373007-77e7743f6684?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2251&q=80")
Field.create!(name: "Robert E. James Park Soccer Field", address: "330 Dodge Ave, Evanston, IL 60202", open_time: DateTime.new(2020, 1, 1, 8, 00, 00), close_time: DateTime.new(2050, 1, 1, 8, 00, 00), image_url: "https://images.pexels.com/photos/114296/pexels-photo-114296.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260")
Field.create!(name: "Rogers Park Soccer Field", address: "7345 N Washtenaw Ave, Chicago, IL 60645", open_time: DateTime.new(2020, 1, 1, 8, 00, 00), close_time: DateTime.new(2050, 1, 1, 8, 00, 00), image_url: "https://images.unsplash.com/photo-1506296756558-7622088b2656?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1782&q=80")

# 20 Scheduled Games
Game.create!(player_id: 1, field_id: 1, date_time: DateTime.new(2020, 8, 26, 11, 00, 00))
Game.create!(player_id: 8, field_id: 2, date_time: DateTime.new(2020, 7, 10, 18, 00, 00))
Game.create!(player_id: 11, field_id: 7, date_time: DateTime.new(2020, 9, 24, 10, 00, 00))
Game.create!(player_id: 11, field_id: 9, date_time: DateTime.new(2020, 10, 5, 12, 00, 00))
Game.create!(player_id: 11, field_id: 13, date_time: DateTime.new(2020, 6, 24, 17, 00, 00))
Game.create!(player_id: 11, field_id: 16, date_time: DateTime.new(2020, 11, 24, 10, 00, 00))
Game.create!(player_id: 11, field_id: 3, date_time: DateTime.new(2020, 11, 24, 18, 00, 00))
Game.create!(player_id: 4, field_id: 6, date_time: DateTime.new(2020, 11, 3, 14, 30, 00))
Game.create!(player_id: 9, field_id: 8, date_time: DateTime.new(2020, 11, 3, 10, 30, 00))
Game.create!(player_id: 3, field_id: 11, date_time: DateTime.new(2021, 4, 3, 12, 30, 00))
Game.create!(player_id: 14, field_id: 15, date_time: DateTime.new(2021, 4, 19, 19, 00, 00))
Game.create!(player_id: 4, field_id: 12, date_time: DateTime.new(2021, 4, 25, 19, 00, 00))
Game.create!(player_id: 2, field_id: 19, date_time: DateTime.new(2021, 4, 27, 19, 00, 00))
Game.create!(player_id: 9, field_id: 4, date_time: DateTime.new(2021, 5, 28, 19, 00, 00))
Game.create!(player_id: 5, field_id: 5, date_time: DateTime.new(2021, 5, 28, 19, 00, 00))
Game.create!(player_id: 9, field_id: 14, date_time: DateTime.new(2021, 5, 28, 19, 00, 00))
Game.create!(player_id: 4, field_id: 11, date_time: DateTime.new(2021, 7, 28, 19, 00, 00))
Game.create!(player_id: 2, field_id: 18, date_time: DateTime.new(2021, 7, 8, 19, 30, 00))
Game.create!(player_id: 7, field_id: 10, date_time: DateTime.new(2021, 7, 8, 19, 00, 00))
Game.create!(player_id: 4, field_id: 20, date_time: DateTime.new(2021, 8, 8, 19, 30, 00))

# Players Attending Games (with 2 players attending and then bailing) <- Maybe a better model name could be GameActivity
PlayerGame.create!(game_id: 1, player_id: 1, attending: true)
PlayerGame.create!(game_id: 1, player_id: 8, attending: true)
PlayerGame.create!(game_id: 1, player_id: 2, attending: true)
PlayerGame.create!(game_id: 1, player_id: 6, attending: true)
PlayerGame.create!(game_id: 1, player_id: 4, attending: true)
PlayerGame.create!(game_id: 1, player_id: 10, attending: true)
PlayerGame.create!(game_id: 1, player_id: 5, attending: true)
PlayerGame.create!(game_id: 1, player_id: 9, attending: true)
PlayerGame.create!(game_id: 1, player_id: 3, attending: false)
PlayerGame.create!(game_id: 1, player_id: 11, attending: true)
PlayerGame.create!(game_id: 2, player_id: 8, attending: true)
PlayerGame.create!(game_id: 2, player_id: 6, attending: true)
PlayerGame.create!(game_id: 2, player_id: 9, attending: true)
PlayerGame.create!(game_id: 2, player_id: 10, attending: true)
PlayerGame.create!(game_id: 2, player_id: 7, attending: false)
PlayerGame.create!(game_id: 2, player_id: 3, attending: true)
PlayerGame.create!(game_id: 2, player_id: 1, attending: true)

PlayerGame.create!(game_id: 3, player_id: 12, attending: true)
PlayerGame.create!(game_id: 3, player_id: 2, attending: true)
PlayerGame.create!(game_id: 3, player_id: 13, attending: true)
PlayerGame.create!(game_id: 3, player_id: 4, attending: true)
PlayerGame.create!(game_id: 3, player_id: 5, attending: true)
PlayerGame.create!(game_id: 3, player_id: 16, attending: true)
PlayerGame.create!(game_id: 3, player_id: 7, attending: true)
PlayerGame.create!(game_id: 3, player_id: 8, attending: true)
PlayerGame.create!(game_id: 4, player_id: 18, attending: true)
PlayerGame.create!(game_id: 4, player_id: 6, attending: true)
PlayerGame.create!(game_id: 4, player_id: 9, attending: true)
PlayerGame.create!(game_id: 4, player_id: 10, attending: true)
PlayerGame.create!(game_id: 4, player_id: 3, attending: true)
PlayerGame.create!(game_id: 4, player_id: 4, attending: true)
PlayerGame.create!(game_id: 4, player_id: 13, attending: true)
PlayerGame.create!(game_id: 5, player_id: 1, attending: true)
PlayerGame.create!(game_id: 5, player_id: 8, attending: true)
PlayerGame.create!(game_id: 5, player_id: 2, attending: true)
PlayerGame.create!(game_id: 5, player_id: 6, attending: true)
PlayerGame.create!(game_id: 5, player_id: 4, attending: true)
PlayerGame.create!(game_id: 5, player_id: 10, attending: true)
PlayerGame.create!(game_id: 5, player_id: 5, attending: true)
PlayerGame.create!(game_id: 5, player_id: 9, attending: true)
PlayerGame.create!(game_id: 6, player_id: 8, attending: true)
PlayerGame.create!(game_id: 6, player_id: 6, attending: true)
PlayerGame.create!(game_id: 6, player_id: 9, attending: true)
PlayerGame.create!(game_id: 6, player_id: 10, attending: true)
PlayerGame.create!(game_id: 6, player_id: 3, attending: true)
PlayerGame.create!(game_id: 6, player_id: 1, attending: true)
PlayerGame.create!(game_id: 7, player_id: 1, attending: true)
PlayerGame.create!(game_id: 7, player_id: 8, attending: true)
PlayerGame.create!(game_id: 7, player_id: 2, attending: true)
PlayerGame.create!(game_id: 7, player_id: 19, attending: true)
PlayerGame.create!(game_id: 7, player_id: 4, attending: true)
PlayerGame.create!(game_id: 7, player_id: 10, attending: true)
PlayerGame.create!(game_id: 7, player_id: 5, attending: true)
PlayerGame.create!(game_id: 7, player_id: 9, attending: true)
PlayerGame.create!(game_id: 8, player_id: 8, attending: true)
PlayerGame.create!(game_id: 8, player_id: 6, attending: true)
PlayerGame.create!(game_id: 8, player_id: 9, attending: true)
PlayerGame.create!(game_id: 8, player_id: 10, attending: true)
PlayerGame.create!(game_id: 8, player_id: 3, attending: true)
PlayerGame.create!(game_id: 8, player_id: 1, attending: true)
PlayerGame.create!(game_id: 9, player_id: 1, attending: true)
PlayerGame.create!(game_id: 9, player_id: 8, attending: true)
PlayerGame.create!(game_id: 9, player_id: 2, attending: true)
PlayerGame.create!(game_id: 9, player_id: 6, attending: true)
PlayerGame.create!(game_id: 9, player_id: 4, attending: true)
PlayerGame.create!(game_id: 9, player_id: 10, attending: true)
PlayerGame.create!(game_id: 9, player_id: 5, attending: true)
PlayerGame.create!(game_id: 9, player_id: 9, attending: true)
PlayerGame.create!(game_id: 10, player_id: 8, attending: true)
PlayerGame.create!(game_id: 10, player_id: 6, attending: true)
PlayerGame.create!(game_id: 10, player_id: 9, attending: true)
PlayerGame.create!(game_id: 10, player_id: 10, attending: true)
PlayerGame.create!(game_id: 10, player_id: 3, attending: true)
PlayerGame.create!(game_id: 10, player_id: 1, attending: true)
PlayerGame.create!(game_id: 11, player_id: 18, attending: true)
PlayerGame.create!(game_id: 11, player_id: 8, attending: true)
PlayerGame.create!(game_id: 11, player_id: 2, attending: true)
PlayerGame.create!(game_id: 11, player_id: 6, attending: true)
PlayerGame.create!(game_id: 11, player_id: 4, attending: true)
PlayerGame.create!(game_id: 11, player_id: 10, attending: true)
PlayerGame.create!(game_id: 11, player_id: 5, attending: true)
PlayerGame.create!(game_id: 11, player_id: 9, attending: true)
PlayerGame.create!(game_id: 12, player_id: 18, attending: true)
PlayerGame.create!(game_id: 12, player_id: 6, attending: true)
PlayerGame.create!(game_id: 12, player_id: 11, attending: true)
PlayerGame.create!(game_id: 12, player_id: 10, attending: true)
PlayerGame.create!(game_id: 12, player_id: 3, attending: true)
PlayerGame.create!(game_id: 12, player_id: 1, attending: true)
PlayerGame.create!(game_id: 13, player_id: 1, attending: true)
PlayerGame.create!(game_id: 13, player_id: 15, attending: true)
PlayerGame.create!(game_id: 13, player_id: 2, attending: true)
PlayerGame.create!(game_id: 13, player_id: 6, attending: true)
PlayerGame.create!(game_id: 13, player_id: 4, attending: true)
PlayerGame.create!(game_id: 13, player_id: 10, attending: true)
PlayerGame.create!(game_id: 13, player_id: 5, attending: true)
PlayerGame.create!(game_id: 13, player_id: 9, attending: true)
PlayerGame.create!(game_id: 14, player_id: 8, attending: true)
PlayerGame.create!(game_id: 14, player_id: 6, attending: true)
PlayerGame.create!(game_id: 14, player_id: 9, attending: true)
PlayerGame.create!(game_id: 14, player_id: 10, attending: true)
PlayerGame.create!(game_id: 14, player_id: 19, attending: true)
PlayerGame.create!(game_id: 14, player_id: 3, attending: true)
PlayerGame.create!(game_id: 14, player_id: 1, attending: true)
PlayerGame.create!(game_id: 15, player_id: 15, attending: true)
PlayerGame.create!(game_id: 15, player_id: 8, attending: true)
PlayerGame.create!(game_id: 15, player_id: 2, attending: true)
PlayerGame.create!(game_id: 15, player_id: 6, attending: true)
PlayerGame.create!(game_id: 15, player_id: 4, attending: true)
PlayerGame.create!(game_id: 15, player_id: 11, attending: true)
PlayerGame.create!(game_id: 15, player_id: 5, attending: true)
PlayerGame.create!(game_id: 15, player_id: 9, attending: true)
PlayerGame.create!(game_id: 16, player_id: 8, attending: true)
PlayerGame.create!(game_id: 16, player_id: 6, attending: true)
PlayerGame.create!(game_id: 16, player_id: 9, attending: true)
PlayerGame.create!(game_id: 16, player_id: 10, attending: true)
PlayerGame.create!(game_id: 16, player_id: 17, attending: true)
PlayerGame.create!(game_id: 16, player_id: 3, attending: true)
PlayerGame.create!(game_id: 16, player_id: 11, attending: true)
PlayerGame.create!(game_id: 17, player_id: 17, attending: true)
PlayerGame.create!(game_id: 17, player_id: 8, attending: true)
PlayerGame.create!(game_id: 17, player_id: 2, attending: true)
PlayerGame.create!(game_id: 17, player_id: 6, attending: true)
PlayerGame.create!(game_id: 17, player_id: 4, attending: true)
PlayerGame.create!(game_id: 17, player_id: 10, attending: true)
PlayerGame.create!(game_id: 17, player_id: 5, attending: true)
PlayerGame.create!(game_id: 17, player_id: 9, attending: true)
PlayerGame.create!(game_id: 17, player_id: 15, attending: true)
PlayerGame.create!(game_id: 18, player_id: 8, attending: true)
PlayerGame.create!(game_id: 18, player_id: 6, attending: true)
PlayerGame.create!(game_id: 18, player_id: 9, attending: true)
PlayerGame.create!(game_id: 18, player_id: 10, attending: true)
PlayerGame.create!(game_id: 18, player_id: 3, attending: true)
PlayerGame.create!(game_id: 18, player_id: 1, attending: true)
PlayerGame.create!(game_id: 19, player_id: 15, attending: true)
PlayerGame.create!(game_id: 19, player_id: 8, attending: true)
PlayerGame.create!(game_id: 19, player_id: 2, attending: true)
PlayerGame.create!(game_id: 19, player_id: 6, attending: true)
PlayerGame.create!(game_id: 19, player_id: 4, attending: true)
PlayerGame.create!(game_id: 19, player_id: 10, attending: true)
PlayerGame.create!(game_id: 19, player_id: 5, attending: true)
PlayerGame.create!(game_id: 19, player_id: 9, attending: true)
PlayerGame.create!(game_id: 20, player_id: 20, attending: true)
PlayerGame.create!(game_id: 20, player_id: 6, attending: true)
PlayerGame.create!(game_id: 20, player_id: 9, attending: true)
PlayerGame.create!(game_id: 20, player_id: 10, attending: true)
PlayerGame.create!(game_id: 20, player_id: 13, attending: true)
PlayerGame.create!(game_id: 20, player_id: 11, attending: true)
